ALTER TABLE `G5CMPE295`.`N_LIST_INFO` 
CHANGE COLUMN `list_id` `list_id` INT(11) NOT NULL AUTO_INCREMENT ;
ALTER TABLE `G5CMPE295`.`N_LIST_PRD` 
CHANGE COLUMN `list_product_id` `list_product_id` INT(11) NOT NULL AUTO_INCREMENT ;
